#!/bin/bash
#set -x
#set -v

# paths seen from windows
RETROARCH_WIN_PATH="D:\RetroArch"
ROM_PATH_WIN="e:\\rom_unpack"

# paths seen from windows wsl
RETROARCH_PATH="/mnt/d/RetroArch"
RETROARCH_WSL_PATH="/mnt/d/Jeux steam/retro/RetroArch"
ROM_PATH="/mnt/e/rom_unpack"

# retroarch config path seen from script ( ~/.config/retroarch/ for linux)
#RETROARCH_PATH="~/.config/retroarch/"
#ROM_PATH="/mnt/rom_directory"

# core definition for windows
EMULATOR_DEF_PATH="/mnt/d/Jeux steam/retro/LaunchBox/Data/Emulators.xml"

# script and utility path 
SCRIPT_PATH="/mnt/d/Telechargements/emulations/script"

# translation string inside rom name to be search (set to empty aka "" for no translation search)
trad="T+Fre"
	
### categorie 
# TODO set by param
#set -x 
#set -v
. ${ROM_PATH}/param_random_retroarch.txt

# Functions
function randomize(){
	MIN=0
	MAX=$(($1-1))
	#echo "max randomize: $1"
	SEED=$(head -1 /dev/urandom | od -N 1 | awk '{ print $2 }')
	RANDOM=$SEED; # init RANDOM
	#random_number_console=$(( ${RANDOM} % MAX + MIN /32767))
	#random_number_game=$(( $SEED % MAX + MIN ))
	random_number=$(( MIN+RANDOM*(MAX - MIN)/32768))
}

function select_console(){
	### CONSOLE
	cd "${ROM_PATH}"
	# list console from directory
	CONSOLES=$(ls -dX */| sed "s/\///") 
	# or define a list of console directory
	CONSOLES="megadrive
	nes
	snes
	mastersystem
	gw"
	# get the number of console
	max_console=$(echo "$CONSOLES" | wc -l)
	# echo "max_console: $max_console"
	
	#generate random number for console selection
	randomize $max_console
	
	i=0
	for current_console in ${CONSOLES}; do
		# exclude of some console
		if [[ 	${i} == ${random_number} &&
				${current_console} != "prboom" &&
				${current_console} != "mrboom" &&
				${current_console} != "doom" &&
				${current_console} != "tyrquake" &&
				${current_console} != "solarus" &&
				${current_console} != "openbor" &&
				${current_console} != "lutro" &&
				${current_console} != "apple2gs" &&
				${current_console} != "amiga600" &&
				${current_console} != "amstradcpc" &&
				${current_console} != "tic80" &&
				${current_console} != "thomson" &&
				${current_console} != "virtualboy" &&
				${current_console} != "satellaview"
			]]; then
			console=${current_console}
			echo -e " Console: ${console}\tRandom number: ${random_number}"
			break
		fi
		i=$(($i+1))
	done
	# manually force current_console
	#current_console="snes"
	#echo -e "${current_console}\t${random_number_console}" 
}

function get_gamelist(){
	# construct the gamelist 
	# 	if a categorie is set get gamelist from the categorie file
	# 	else
	#		if on linux from the gamelist.xml file 
	#		if on windows from listing of console directory
	currentPlaylist="${ROM_PATH}/${current_console}/gamelist.xml"
	
	# if a categorie is define and the file that define the list of game of this categorie exist
	if [[ -v categorie  && -f ${ROM_PATH}/${current_console}/${categorie}_list.txt ]] ;then 
		echo " Categorie: ${categorie}"
		# search for current console entry in the global _launchedgames.txt file
		# and search all that is not in _launchedgames from the game categorie file
		# to construct the game list
		gamelist=$(grep -i ${current_console} ${ROM_PATH}/_launchedgames.txt |cut -d'_' -f2- | sed 's/ (.*//' | sed '/ $/d'| grep -viFf - ${ROM_PATH}/${current_console}/${categorie}_list.txt)
	else 
		# if a saga is define
		if [[ -v saga ]] ;then
			echo " Saga: ${saga}"
			# get all game of the current console that contains saga name
			gamelist=$(ls ${ROM_PATH}/${current_console} | grep -iE "${saga}"|sort -n)
		# else get list of games
		else			
			if [ $(cat /proc/version | grep -c microsoft) == 0 ] ; then
				# LINUX json playlist
				gamelist=$(grep '"path' "$currentPlaylist" | cut -d ':' -f2 | sed 's/",$//' | sed 's/^ "//' )
			else
				# windows new format not compressed
				# gamelist retroarch
				#old #gamelist=$(grep '"path' "$RETROARCH_PLAYLIST/$currentPlaylist" | cut -d '"' -f4 | sed 's/",$//' | sed 's/^ "//')
				#gamelist=$(grep "<path>" $currentPlaylist | sed "s/.*<path>\.\/\(.*\)<\/path>/\1/")
				gamelist=$(ls -p ${ROM_PATH}/${current_console} | grep -ve "\.srm" -ve "\.txt" -ve "\.xml" -ve "/") #list game in directory
			fi
		fi
	fi
	#echo "$gamelist"
}

function search_rom(){
	tmpname=""
	# main prefered language
	main_country="Fr F"
	# alternative language with precedence order
	other_country="E Eu Europe UE U USA JUE JE J Japan Unl PD W K AVE"
	for country in ${main_country}; do # check Fr
		if [[ "${tmpname}" == "" ]] ; then # good dump [!]
			tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) \[!\]\.") 
		fi
		if [[ "${tmpname}" == "" ]] ; then # without information
			tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country})\.") 
		fi
		if [[ "${tmpname}" == "" ]] ; then # with anything inside []
			tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) \[.*\]\.") 
		fi
		if [[ "${tmpname}" == "" ]] ; then # with anything inside () and []
			tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) (.*) \[.*\]\.")
		fi
		if [[ "${tmpname}" == "" ]] ; then # with anything inside ()
			tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) (.*)\.") 
		fi
		if [[ "${tmpname}" != "" ]] ; then # if found set it to the rom var
			rom=$tmpname
			break
		fi
	done
	# if search_rom is called with a translation parameter filter search for specified translation
	if [[ $1 != "" ]];then
		for country in ${other_country}; do # check all other with trad [T+...] given in parameter
			if [[ "${tmpname}" == "" ]] ; then # trad [T+...]
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) \[${1}.*\]\.") 
			fi
			if [[ "${tmpname}" == "" ]] ; then # anything trad Fr [T+...]
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) (.*) \[${1}.*\]\.") 
			fi
			if [[ "${tmpname}" != "" ]] ; then # if found set it to the rom var
				rom=$tmpname
				break
			fi
		done
	else
		for country in ${other_country}; do # check all other without trad
			if [[ "${tmpname}" == "" ]] ; then # good dump [!]
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) \[!\]\.") 
			fi
			if [[ "${tmpname}" == "" ]] ; then # without information
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country})\.") 
			fi
			if [[ "${tmpname}" == "" ]] ; then # with anything inside []
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) \[.*\]\.") 
			fi
			if [[ "${tmpname}" == "" ]] ; then # with anything inside () and []
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) (.*) \[.*\]\.") 
			fi
			if [[ "${tmpname}" == "" ]] ; then # with anything inside ()
				tmpname=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext} (${country}) (.*)\.") 
			fi
			if [[ "${tmpname}" != "" ]] ; then # if found set it to the rom var
				rom=$tmpname
				break
			fi
		done
	fi
}

function select_game(){
	### Select a rom
	# 	or from the gamelist.xml file 
	#	or from listing directory
	# 	or if a categorie is set from the categorie file list
	
	# number of game in the playlist
	maxgame=$(echo "$gamelist"| sed '/^$/d' | wc -l)
	if [[ ${maxgame} -eq 0 ]]; then
		echo "No game matching for ${console}"
		is_a_listed_game=0
		return
	fi
	# randomly choose a game from the playlist
	randomize ${maxgame}
	# select the game matching random number position in the playlist
	i=0
	OIFS=$IFS
	IFS=$'\n'
	for rom in ${gamelist}; do
		if [ ${i} == ${random_number} ]; then
			echo -e " Game: ${rom}\tRandom number: ${random_number}"
			break
		fi
		i=$(($i+1))
	done
	IFS=$OIFS
	
	#remove selected rom from the gamelist
	gamelist=$(echo "$gamelist" | sed "/${rom}/d")
	#echo "Game list: $gamelist"
	
	# list all roms that contains rom name
	#rom="Faxanadu"
	rom=$(echo ${rom} | sed 's/\&amp;/\&/g' )
	rom_w_ext=$(echo ${rom} |sed -e 's/ (.*)//g' -e 's/ \[.*\]//g' -e 's/\..*//g') # remove extention in rom name depend if name come from xml or file list
	
	#echo "rom: ${rom}" 
	#echo "all rom matching name ${rom_w_ext}: "
	#echo "	$(ls ${ROM_PATH}/${current_console}/ | grep -ie "^${rom_w_ext}")" 


	search_rom ${trad}
	# if the rom var is empty find any trad EN matching rom
	if [[ "${tmpname}" == "" ]]; then  
		trad="T+Eng"
		search_rom ${trad}
	fi
	if [[ "${tmpname}" == "" ]]; then 
		search_rom
	fi
	# TODO: improve categorie search
	if [[ -v categorie ]]; then
		# if the rom var is empty find any matching rom 
		if [[ "${tmpname}" == "" ]] ; then 
			# TODO: manage r-type 3 / ganada && multiple rom matching
			rom=$(ls ${ROM_PATH}/${current_console}/ | grep -ie "${rom_w_ext}.*\.")
		fi
	fi

	#echo "$gamelist"
	## if file for launchedgame doesn't exist create it
	if [[ ! -f ${categorie}_launchedgames.txt ]]; then 
		touch ${categorie}_launchedgames.txt
	fi
	# if the game is not found in the launchedgames list file add it and exit
	if [[ $(grep -c -F "${console}_${rom}" ${categorie}_launchedgames.txt) == 0 ]] ; then 
		echo "${console}_${rom}" >> ${categorie}_launchedgames.txt
		is_a_listed_game=0 # var for the until loop
	fi
	# clear the laucnhed games file if the number of game for this console is reached
	if [[ $(grep -c -F "${console}" ${categorie}_launchedgames.txt) -ge ${maxgame} ]] ; then 
		sed "/${console}.*/d" -i ${categorie}_launchedgames.txt
	fi
}

function get_core(){
	# get the core for the game
	# on linux from the gamelist.xml
	# on windows from launchbox file
	if [ $(cat /proc/version | grep -c microsoft) == 0 ] ; then
		# get it from linux playlist
		core=$(grep '"default_core_path' "$RETROARCH_PLAYLIST/$currentPlaylist" | cut -d ':' -f2 | sed 's/",$//' | sed 's/^ "//')
	else
		# get core from gamelist game core or gamelist default core or launchbox list
		# core="-L \""$(grep -A2 -F "${rom}" "$RETROARCH_PLAYLIST/$currentPlaylist" | grep "core" | cut -d'"' -f4)"\""
		# if [[ "${core}" == "-L \"\"" || "${core}" == "-L \"DETECT\"" ]] ;then
			# # old 
			# #core=$(grep '"default_core_path' "$RETROARCH_PLAYLIST/$currentPlaylist" | cut -d '=' -f3 |sed 's/^ //')
			# # 
			# core="-L \""$(grep '"default_core_path' "$RETROARCH_PLAYLIST/$currentPlaylist" | cut -d '"' -f4 |sed 's/^ //')"\""
			# if [ "${core}" == "-L \"\"" ] ;then
				core=$(grep -A1 ">${current_console}<" "${EMULATOR_DEF_PATH}" | grep Command | sed 's/.*>\(.*\)<.*/\1/')
				#echo ${core}
			# fi
		# fi
	fi
}


function generate_obs_title(){
	# generate html for obs from template file
	sed -e "s/CONSOLE/${current_console}/g" -e "s/CURRENTGAME/${current_game}/g" ${SCRIPT_PATH}/retro.html.template >  ${SCRIPT_PATH}/retro.html
}

function set_stream_title(){
	# generate script content to set the good title
	if [[ -v categorie ]] ; then
		sed -e "s/TITLE/${current_game} un ${categorie} sur la ${current_console}/g"  ${SCRIPT_PATH}/set_game_title.sh >  ${SCRIPT_PATH}/set_current_game_title.sh
	else
		sed -e "s/TITLE/${current_game} sur la ${current_console}/g"  ${SCRIPT_PATH}/set_game_title.sh >  ${SCRIPT_PATH}/set_current_game_title.sh
	fi
	# call the api script to change twitch title
	bash ${SCRIPT_PATH}/set_current_game_title.sh
}

function start_game(){
	# start the game or the emulator
	# on windows generated html for obs 
	# and execute twitch api command to change stream title
	if [ $(cat /proc/version | grep -c microsoft) == 0 ] ; then
		retroarch ${core} "${ROM_PATH}/${current_console}/${rom}"
	else
		# rom="SD Ultra Battle - Seven & Ultraman + ST BIOS (ST) [h1][o1].smc"
		# current_console="snes"
		echo " core: ${core}"
		echo " rom: ${rom}"
		if [ "${core}" != "" ] ; then
			current_game=$(echo ${rom%.*} |sed -e "s/&/\\\&/g")
			echo " game ${current_game}"
			if [[ -v obs ]]; then
				generate_obs_title
			fi
			if [[ -v stream ]]; then
				set_stream_title
			fi 
			# force specific  standalone emulator to be use for some console
			case ${current_console} in
				"atarist")
					echo '"'D:\\Jeux steam\\retro\\hatari-2.4.1_windows64\\hatari.exe'"' '"'${ROM_PATH_WIN}/${current_console}/${rom}'"'
					exit
					;;
				# "psx")
					# echo '"'D:\\Jeux steam\\retro\\epsxe\\epsxe.exe'"' -nogui  -loadbin '"'${rom}'"'
					# exit
					# ;;
				"3ds")
					echo '"'D:\\Jeux steam\\retro\\Citra\\nightly\\citra-qt.exe'"' '"'${ROM_PATH_WIN}/${current_console}/${rom}'"'
					exit
					;;
				"ps2")
					echo '"'D:\\Jeux steam\\retro\\PCSX2 1.4.0\\pcsx2.exe'"' --fullscreen '"'${ROM_PATH_WIN}/${current_console}/${rom}'"'
					exit
					;;
			esac
			# echo the return for windows batch execute command
			echo "${RETROARCH_WIN_PATH}\retroarch.exe -f " ${core} '"'${ROM_PATH_WIN}\\${current_console}\\${rom}'"'
		else # echo no core found for the console
			echo "set /p end=No core for ${current_console}"
		fi
	fi
}

### Main 
# set console
console=""
while [[ ${console} == "" ]] ; do 
	select_console
done
get_gamelist

is_a_listed_game=1
until [[ ${is_a_listed_game} == 0 ]]; do                                      
	currentPlaylist="${ROM_PATH}/${current_console}/gamelist.xml" # playlist directory
	if [[ -f "${currentPlaylist}" ]] ;then # if there is no gamelist in the directory 
		select_game
	fi
done
get_core
start_game